// <auto-generated />
using System;
using CedarRisk.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CedarRisk.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CedarRiskDbContext))]
    partial class CedarRiskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CedarRisk.Domain.GarantieConditions.GarantieCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AgeLimiteVehicule")
                        .HasColumnType("integer")
                        .HasColumnName("age_limite_vehicule");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExigenceConjonctive")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("exigence_conjonctive");

                    b.Property<string>("ExigenceDisjonctive")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("exigence_disjonctive");

                    b.Property<string>("GarantieCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("garantie_code");

                    b.Property<string>("Incompatibilites")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("incompatibilites");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("_usagesExclus")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("usages_exclus");

                    b.HasKey("Id");

                    b.HasIndex("GarantieCode")
                        .IsUnique()
                        .HasDatabaseName("uix_garantie_conditions_code_active")
                        .HasFilter("is_active = true");

                    b.HasIndex("GarantieCode", "IsActive")
                        .HasDatabaseName("ix_garantie_conditions_code_active");

                    b.ToTable("garantie_conditions", (string)null);
                });

            modelBuilder.Entity("CedarRisk.Domain.GarantieTarifications.GarantieTarification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EstSoumisACatNat")
                        .HasColumnType("boolean")
                        .HasColumnName("est_soumis_a_catnat");

                    b.Property<string>("GarantieCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("garantie_code");

                    b.Property<string>("ModeTarifaire")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("mode_tarifaire");

                    b.Property<int?>("SupersededById")
                        .HasColumnType("integer")
                        .HasColumnName("superseded_by_id");

                    b.Property<decimal>("TauxCatNatGC")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("taux_catnat_gc");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("GarantieCode", "ValidFrom")
                        .HasDatabaseName("ix_garantie_tarifications_code_validfrom");

                    b.HasIndex("GarantieCode", "ValidTo")
                        .IsUnique()
                        .HasDatabaseName("uix_garantie_tarifications_code_open")
                        .HasFilter("valid_to IS NULL");

                    b.ToTable("garantie_tarifications", (string)null);
                });

            modelBuilder.Entity("CedarRisk.Domain.Garanties.GarantieDefinition", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("libelle");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_garantie_definitions_is_active");

                    b.ToTable("garantie_definitions", (string)null);
                });

            modelBuilder.Entity("CedarRisk.Domain.ReferentielTarifaires.ReferentielTarifaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("TarifRemorque")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("tarif_remorque");

                    b.Property<decimal>("TauxCatNatRC")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("taux_catnat_rc");

                    b.Property<decimal>("TauxParafiscaleGC")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("taux_parafiscale_gc");

                    b.Property<decimal>("TauxParafiscaleRC")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("taux_parafiscale_rc");

                    b.Property<decimal>("TauxTaxeGC")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("taux_taxe_gc");

                    b.Property<decimal>("TauxTaxeRC")
                        .HasColumnType("numeric(6,5)")
                        .HasColumnName("taux_taxe_rc");

                    b.Property<decimal>("TimbreCNPAC")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("timbre_cnpac");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("Id");

                    b.HasIndex("ValidFrom")
                        .HasDatabaseName("ix_referentiel_tarifaires_valid_from");

                    b.ToTable("referentiel_tarifaires", (string)null);
                });

            modelBuilder.Entity("CedarRisk.Domain.ReferentielTarifaires.ValueObjects.BaremeRC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PrimeHT")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("prime_ht");

                    b.Property<int?>("PuissanceMax")
                        .HasColumnType("integer")
                        .HasColumnName("puissance_max");

                    b.Property<int>("PuissanceMin")
                        .HasColumnType("integer")
                        .HasColumnName("puissance_min");

                    b.Property<int>("ReferentielTarifaireId")
                        .HasColumnType("integer");

                    b.Property<string>("Usage")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("usage");

                    b.Property<int>("referentiel_tarifaire_id")
                        .HasColumnType("integer")
                        .HasColumnName("referentiel_tarifaire_id");

                    b.HasKey("Id");

                    b.HasIndex("referentiel_tarifaire_id", "Usage", "PuissanceMin")
                        .IsUnique()
                        .HasDatabaseName("ix_bareme_rc_referentiel_usage_puissance");

                    b.ToTable("bareme_rc", (string)null);
                });

            modelBuilder.Entity("CedarRisk.Domain.ReferentielTarifaires.ValueObjects.BaremeRC", b =>
                {
                    b.HasOne("CedarRisk.Domain.ReferentielTarifaires.ReferentielTarifaire", null)
                        .WithMany("Bareme")
                        .HasForeignKey("referentiel_tarifaire_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CedarRisk.Domain.ReferentielTarifaires.ReferentielTarifaire", b =>
                {
                    b.Navigation("Bareme");
                });
#pragma warning restore 612, 618
        }
    }
}
